# *- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

server_ip = "192.168.56.110"

scriptserver = <<-SHELL
	sudo -i
	apk add curl
	echo I am provisioning server...
	export INSTALL_K3S_EXEC="--bind-address=#{server_ip} --node-external-ip=#{server_ip} --flannel-iface=eth1"
SHELL



Vagrant.configure("2") do |config|
  index = 1
  
  config.vm.box = "generic-x64/debian12"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1    # create a master VM before creating the linked clones
    vb.linked_clone = true
  end

  # config.vm.box = "generic/debian12"
  config.vm.box = "generic/alpine318"
  config.vm.define "Server" do |serv|
    serv.vm.network "private_network", ip: server_ip
    serv.vm.synced_folder "./shared", "/vagrant_shared"
    serv.vm.hostname = "server-node"
    serv.vm.provision "shell", inline: scriptserver
  end
end
