# *- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

server_ip = "192.168.56.110"

Vagrant.configure("2") do |config|
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 8   # create a master VM before creating the linked clones
    vb.linked_clone = true
  end

  config.vm.box = "generic/alpine318"
  config.vm.define "Server" do |serv|
    serv.vm.network "private_network", ip: server_ip
    serv.vm.synced_folder "./shared", "/vagrant_shared"
    serv.vm.hostname = "server-node"
    serv.vm.provision "shell", path: "provision.sh"
    serv.vm.provision "shell", path: "user_provisioning.sh", privileged: false
  end
end
