apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-host-routing
spec:
 rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ngs-app3
            port:
              number: 80

