apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngd

spec:
  replicas: 3
  template:
    metadata:
    spec:
      volumes:
        - name: config-volume
          hostPath:
            path: /vagrant_shared/app2.html
            type: File
